app/estoque/routes.py
from flask import Blueprint, request, session, render_template, redirect, flash, url_for
from datetime import date, datetime
from sqlalchemy.orm import Session as S

from app.utils import login_required, role_required
from app.database.db import *
from app.database.utils import *
from app.utils import somar_dia
from app.estoque.models import *
from app.models import *
from app.empenho.models import *
from app.usuarios.models import Usuario

estoque_bp = Blueprint('estoque', __name__, template_folder='templates')


@estoque_bp.route('/movimentacoes-diarias', methods=['POST', 'GET'])
@login_required
def movimentacoes_diarias():
    tipo_movimentacao = request.values.get('tipo_movimentacao')
    if not tipo_movimentacao:
        tipo_movimentacao = session.pop('tipo_movimentacao', None)
    if not tipo_movimentacao:
        tipo_movimentacao = 'saida'

    data = request.form.get('date')
    if data == None:
        data = session.pop('date', None)
    if data == None:
        data = date.today().isoformat()

    with get_session() as session_db:
        entradas_diarias = session_db.query(Entrada).filter_by(data_entrada=data).order_by(Entrada.produto_id).all()
        saidas_diarias = session_db.query(Saida).filter_by(data_saida=data).order_by(Saida.refeicao_id).order_by(Saida.produto_id).all()

        produtos_dict, fornecedores_dict, marcas_dict, refeicoes = get_additional_info(session_db)
        saldos_diarios = session_db.query(SaldoDiario).filter_by(data=data).all()
        nfs_1 = session_db.query(
            NotaFiscal
        ).join(
            Empenho, Empenho.id == NotaFiscal.empenho_id
        ).join(
            Ata, Ata.id == Empenho.ata_id
        ).filter(
            Ata.tipo == 'nao_perecivel'
        ).group_by(
            NotaFiscal.id
        ).all()
        nfs_2 = session_db.query(NotaFiscal).filter_by(id=1).all()
        nota_fiscal_dict = {nf.id: nf for nf in nfs_2 + nfs_1}

        dia = session_db.query(DiasFechados).filter_by(data=data).first()

        movs = entradas_diarias.copy()
        movs.extend(saidas_diarias.copy())

        usuarios = {}
        for mov in movs:
            if mov.usuario_id not in usuarios.keys():
                usuario = session_db.query(Usuario).filter_by(id=mov.usuario_id).first()
                if usuario:
                    usuarios[usuario.id] = usuario.nome
                else:
                    usuarios[mov.usuario_id] = 'Desconhecido'

    return render_template(
        'estoque/movimentacoes_diarias.html',
        saidas=saidas_diarias,
        data=data,
        produtos=produtos_dict,
        entradas=entradas_diarias,
        saldos_diarios=saldos_diarios,
        dia=dia,
        usuarios=usuarios,
        fornecedores=fornecedores_dict,
        marcas=marcas_dict,
        notas_fiscais=nota_fiscal_dict,
        refeicoes=refeicoes,
        tipo_movimentacao=tipo_movimentacao
    )

@estoque_bp.route('/fechar/dia/<data>')
@login_required
@role_required('admin', 'nutricionista')
def fechar_dia(data: str):
    cod = verificar_dias_abertos()
    if cod == 1:
        flash('Não há dia aberto', 'danger')
        return
    
    try:
        with get_session() as session_db:
            saldos_ = session_db.query(SaldoDiario).filter_by(data=data).all()

            if not check_saldo(data, session_db):
                return redirect(url_for('estoque.movimentacoes_diarias', date=data))

            dia = session_db.query(DiasFechados).filter_by(data=data).first()
            dia.fechado = True

            # Soma 1 dia a data
            new_date = somar_dia(data, '%Y-%m-%d')

            dia = DiasFechados(data=new_date, fechado=False)
            session_db.add(dia)

            for saldo in saldos_:
                new_saldo = SaldoDiario(produto_id=saldo.produto_id, data=new_date, quantidade_inicial=saldo.quantidade_final, quantidade_entrada=0, quantidade_saida=0, quantidade_final=saldo.quantidade_final)
                session_db.add(new_saldo)
    except Exception as e:
        flash(f'Falha ao fechar dia: {data}', 'danger')
    else:
        try:
            data_formatada = datetime.strptime(data, "%Y-%m-%d").strftime("%d/%m/%Y")
            flash(f"Dia {data_formatada} fechado com sucesso", 'success')
        except Exception as e:
            flash(f'Dia {data} fechado com sucesso', 'success')
    
    session['date'] = data
    return redirect(url_for('estoque.movimentacoes_diarias'))




def get_additional_info(session_db: S):
    produtos_dict = {p.id: p for p in session_db.query(Produto).all()}
    fornecedores_dict = {f.id: f for f in session_db.query(Fornecedor).all()}
    marcas_dict = {m.id: m for m in session_db.query(Marca).order_by(Marca.nome).all()}
    refeicoes = {d.id: d for d in session_db.query(Refeicao).all()}

    return produtos_dict, fornecedores_dict, marcas_dict, refeicoes



@estoque_bp.route('/movimentacao/<int:produto_id>/')
@login_required
def movimentacao_por_produto(produto_id):
    page = request.args.get('page', default=1, type=int)
    p_page = 20
    offset = (page - 1) * p_page
    movimentacoes: list[dict] = []
    logs_saidas = {}
    logs_entradas = {}
    total = 0
    
    try:
        movimentacoes, total = list_movementation_by_product(produto_id, p_page, offset)
        with get_session() as session_db:
            produto = session_db.query(Produto).filter_by(id=produto_id).first()
            refeicoes = {d.id: d for d in session_db.query(Refeicao).all()}
            usuarios = {u.id: u for u in session_db.query(Usuario).all()}
            
            for movimentacao in movimentacoes:
                log = session_db.query(Log).filter_by(operacao_id=movimentacao.get('id')).filter_by(tipo_operacao_2='inserção').filter_by(tipo_operacao=movimentacao.get('tipo')).first()
                if log:
                    if movimentacao.get('tipo') == 'saida':
                        logs_saidas[movimentacao['id']] = log
                    elif movimentacao.get('tipo') == 'entrada':
                        logs_entradas[movimentacao['id']] = log

    except Exception as e:
        flash(f'{e}', 'danger')
        return redirect('/')
    
    if produto == None:
        flash('Produto não encontrado', 'danger')
        return redirect('/')
    
    produto.nome = produto.nome.replace('\n', ' ')
    total_pages = (total + p_page - 1) // p_page

    return render_template('estoque/movimentacao_por_produto.html', movimentacoes=movimentacoes, produto=produto, refeicoes=refeicoes, page=page, total_pages=total_pages, usuarios=usuarios, logs_saidas=logs_saidas, logs_entradas=logs_entradas)


def verificar_dias_abertos() -> int:
    try:
        with get_session() as session_db:
            dias_ = session_db.query(DiasFechados).filter_by(fechado=False).all()

            if len(dias_) == 0:
                mais_recente = session_db.query(DiasFechados).filter_by(fechado=True).order_by(DiasFechados.data.desc()).first()
                if mais_recente == None:
                        return 1
            
            elif len(dias_) > 1:
                for dia in dias_[:-1]:
                    dia.fechado = True
                return 2
    except Exception as e:
        flash(f'Não foi possivel verificar os dias: {e}', 'danger')
        return 3
    
    return 0

app/estoque/templates/estoque/marcas.html
{% extends 'base.html' %}

{% block content %}


<div>
  <a href="{{ url_for('main.estoque_menu') }}" class="btn btn-secondary m-3">
    <i class="bi bi-arrow-left"></i>
  </a>
</div>


<div class="container py-4">
  <div class="page-title mb-4">
    <h2 class="fw-bold border-bottom pb-2">
      Marcas
    </h2>
  </div>
</div>

{% if ['admin', 'nutricionista'] | check_intersection(session.get('roles')) %}
<div style="display: flex; justify-content: center;">
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#cadastroMarcaModal" style="margin: 10px;">
    Cadastrar nova marca
  </button>
</div>
{% endif %}

<div class="container mt-5">
<div class="card mb-3 shadow" style="border: 0px; padding: 30px; border-radius: 15px;">
  <div class="card-body">
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">Produto</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for marca in marcas %}
        {% if marca.produto_id != None %}
        <tr>
          <td>{{ marca.nome }}</td>
          <td>{{ produtos[marca.produto_id].nome }}</td>
          <td style="display: flex; gap: 10px;">
          {% if ['admin', 'nutricionista'] | check_intersection(session.get('roles')) %}
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editMarcaModal"
            data-id="{{ marca.id }}"
            data-nome="{{ marca.nome }}"
            data-produto="{{ marca.produto_id}}">
            Editar
          </button>
          {% else %}
          <button class="btn btn-secondary" onclick="alert('Você não tem permissão para editar este item.')">Editar</button>
          {% endif %}
          </td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
</div>
</div>


{% if marcas | length > 0 %}
<nav aria-label="Navegação de páginas">
  <ul class="pagination justify-content-center">

    {% if page > 1 %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('marcas.marcas_lista', page=page-1) }}">
          Anterior
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">Anterior</span>
      </li>
    {% endif %}

    <li class="page-item disabled">
      <span class="page-link">
        Página {{ page }} de {{ total_pages }}
      </span>
    </li>

    {% if page < total_pages %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('marcas.marcas_lista', page=page+1) }}">
          Próxima
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">Próxima</span>
      </li>
    {% endif %}

  </ul>
</nav>
{% endif %}

<!-- Modal Cadastro -->
<div class="modal fade" id="cadastroMarcaModal" tabindex="-1" aria-labelledby="cadastroMarcaModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <form action="{{ url_for('marcas.cadastro_marca') }}" method="POST">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="cadastroMarcaModalLabel">Cadastrar Marca</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
        </div>
        <div class="modal-body">
          <div class="mb-3">
            <label for="nome" class="form-label">Nome</label>
            <input id="nome" name="nome" type="text" class="form-control" required>
          </div>

          <div class="mb-3">
            <label for="produto_id" class="form-label">Produto</label>
            <select id="produto_id" name="produto_id" class="form-select" required>
              {% for p_id, p in produtos.items() %}
                {% if p.status == 'ativo' or 'admin' in session.get('roles', []) %}
                  <option value="{{ p_id }}">{{ p.nome }}</option>
                {% endif %}
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
          <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal Editar -->
<div class="modal fade" id="editMarcaModal" tabindex="-1" aria-labelledby="editMarcaModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <form id="editMarcaForm" method="POST">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="editMarcaModalLabel">Editar Marca</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
        </div>
        <div class="modal-body">
          <div class="mb-3">
            <label for="edit_nome" class="form-label">Nome</label>
            <input id="edit_nome" name="edit_nome" type="text" class="form-control" required>
          </div>

          <div class="mb-3">
            <label for="edit_produto_id" class="form-label">Produto</label>
            <select id="edit_produto_id" name="edit_produto_id" class="form-select" required>
              {% for p_id, p in produtos.items() %}
                {% if p.status == 'ativo' or 'admin' in session.get('roles', []) %}
                  <option value="{{ p_id }}">{{ p.nome }}</option>
                {% endif %}
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script>
    document.querySelectorAll('[data-bs-target="#editMarcaModal"]').forEach(button => {
  button.addEventListener('click', () => {
    document.getElementById("edit_nome").value = button.dataset.nome;
    document.getElementById("edit_produto_id").value = button.dataset.produto;
    document.getElementById("editMarcaForm").action = "{{ url_for('marcas.editar_marca', marca_id=0) }}".replace('0', button.dataset.id);
  });
});

  const modal = document.getElementById('cadastroMarcaModal');
  modal.addEventListener('shown.bs.modal', function () {
    const input = document.getElementById('nome');
    input.focus();
  });

  const editModal = document.getElementById('editMarcaModal');
  editModal.addEventListener('shown.bs.modal', function () {
    const input = document.getElementById('edit_nome');
    input.focus();
  });

</script>

{% endblock %}

app/estoque/templates/estoque/movimentacao_por_produto.html
{% extends 'base.html' %}

{% block content %}

<div>
  <a href="{{ url_for('produtos.produtos_lista') }}" class="btn btn-secondary m-3">
    <i class="bi bi-arrow-left"></i>
  </a>
</div>

<div class="container py-4">
  <div class="page-title mb-4">
    <h2 class="fw-bold border-bottom pb-2">
        Movimentação de {{ produto.nome }}
    </h2>
  </div>
</div>

{% if movimentacoes | length > 0 %}
<div class="container mt-5">
    <div class="table-responsive">

        <table class="table table-striped table-bordered table-hover">
        <thead class="table-dark">
            <tr>
                <th scope="col">Data</th>
                <th scope="col">Tipo</th>
                <th scope="col">Quantidade</th>
                <th scope="col">Responsavel</th>
                <th scope="col">Refeição</th>
                <th scope="col">Data de registro</th>
                <th scope="col">Observação</th>
            </tr>
        </thead>
        
        <tbody>

            {% for movimentacao in movimentacoes %}
                <tr>
                    <td scope="row">{{ movimentacao.get('data') | format_date }}</td>
                    <td>{{ movimentacao.get('tipo', '').capitalize() }}</td>
                    <td>{{ movimentacao.get('quantidade') }}</td>
                    <td>{{ usuarios.get(movimentacao.get('responsavel')).nome }}</td>
                    <td>{{ refeicoes.get(movimentacao.get('refeicao_id')).nome }}</td>
                    {% if logs_saidas.get(movimentacao.get('id')) or logs_entradas.get(movimentacao.get('id')) %}
                      {% if movimentacao.get('tipo') == 'saida' %}
                          <td>{{ logs_saidas.get(movimentacao.get('id')).data_hora | format_date('%d/%m/%Y %H:%M:%S') }}</td>
                        {% elif movimentacao.get('tipo') == 'entrada' %}
                          <td>{{ logs_entradas.get(movimentacao.get('id')).data_hora | format_date('%d/%m/%Y %H:%M:%S') }}</td>
                        {% endif %}
                    {% else %}
                      <td>-</td>
                    {% endif %}
                    <td>{{ movimentacao.get('observacao') }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
{% else %}
<div style="display: flex; justify-content: center;">
  <p>Não há movimentações desse produto</p>
</div>
{% endif %}
<!-- Container de paginação -->

{% if movimentacoes | length > 0 %}
<nav aria-label="Navegação de páginas">
  <ul class="pagination justify-content-center">

    <!-- Link Anterior -->
    {% if page > 1 %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('estoque.movimentacao_por_produto', produto_id=produto.id, page=page-1) }}">
          Anterior
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">Anterior</span>
      </li>
    {% endif %}

    <!-- Texto central mostrando a página atual -->
    <li class="page-item disabled">
      <span class="page-link">
        Página {{ page }} de {{ total_pages }}
      </span>
    </li>

    <!-- Link Próxima -->
    {% if page < total_pages %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('estoque.movimentacao_por_produto', produto_id=produto.id, page=page+1) }}">
          Próxima
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">Próxima</span>
      </li>
    {% endif %}

  </ul>
</nav>
{% endif %}

{% endblock %}

app/estoque/templates/estoque/movimentacoes_diarias.html
{% extends 'base.html' %}

{% block content %}


<div>
  <a href="{{ url_for('main.estoque_menu') }}" class="btn btn-secondary m-3">
    <i class="bi bi-arrow-left"></i>
  </a>
</div>


<div class="container py-4">
  <div class="page-title mb-4">
    <h2 class="fw-bold border-bottom pb-2">
      Movimentações diárias
    </h2>
  </div>
</div>


<div class="container py-4">

<div class="card mb-3 shadow" style="border: 0px; border-radius: 15px;">
    <div class="card-body d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3">
      <form id="formData" action="{{ url_for('estoque.movimentacoes_diarias') }}" class="d-flex align-items-center gap-2" method="post">
        <input type="date" id="date" name="date" value="{{ data }}" class="form-control">
      </form>

{% if dia %}
    {% if dia.fechado %}
        <div class="alert alert-warning">
          Status do dia: <strong>Fechado</strong>
        </div>  
      {% else %}
        <div class="alert alert-success">
          Status do dia: <strong>Aberto</strong>
        </div>  
      {% endif %}
{% else %}
    <div class="alert alert-secondary">
      Status do dia: <strong>Indisponivel</strong>
    </div>  
{% endif %}
</div>
</div>
</div>


<ul class="nav nav-tabs justify-content-center" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    {% if tipo_movimentacao == 'saida' %}
      <button class="nav-link active" id="saidas-tab" data-bs-toggle="tab" data-bs-target="#saidas-tab-pane" type="button" role="tab" aria-controls="saidas-tab-pane" aria-selected="true">Saidas</button>
    {% else %}
      <button class="nav-link" id="saidas-tab" data-bs-toggle="tab" data-bs-target="#saidas-tab-pane" type="button" role="tab" aria-controls="saidas-tab-pane" aria-selected="false">Saidas</button>
    {% endif %}     
  </li>
  <li class="nav-item" role="presentation">
    {% if tipo_movimentacao == 'entrada' %}
      <button class="nav-link active" id="entradas-tab" data-bs-toggle="tab" data-bs-target="#entradas-tab-pane" type="button" role="tab" aria-controls="entradas-tab-pane" aria-selected="true">Entradas</button>
    {% else %}
      <button class="nav-link" id="entradas-tab" data-bs-toggle="tab" data-bs-target="#entradas-tab-pane" type="button" role="tab" aria-controls="entradas-tab-pane" aria-selected="false">Entradas</button>
    {% endif %}
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="saldo-tab" data-bs-toggle="tab" data-bs-target="#saldo-tab-pane" type="button" role="tab" aria-controls="saldo-tab-pane" aria-selected="false">Saldo diário</button>
  </li>
</ul>


<div class="tab-content" id="myTabContent">

{% if tipo_movimentacao == 'saida' %}
  <div class="tab-pane fade show active" id="saidas-tab-pane" role="tabpanel" aria-labelledby="saidas-tab" tabindex="0">
{% else %}
  <div class="tab-pane fade" id="saidas-tab-pane" role="tabpanel" aria-labelledby="saidas-tab" tabindex="0">
{% endif %}

{% include 'estoque/partials/saidas_table.html' %}

</div>

{% if tipo_movimentacao == 'entrada' %}
  <div class="tab-pane fade show active" id="entradas-tab-pane" role="tabpanel" aria-labelledby="entradas-tab" tabindex="0">
{% else %}
  <div class="tab-pane fade" id="entradas-tab-pane" role="tabpanel" aria-labelledby="entradas-tab" tabindex="0">
{% endif %}

{% include 'estoque/partials/entradas_table.html' %}

</div>
<div class="tab-pane fade" id="saldo-tab-pane" role="tabpanel" aria-labelledby="saldo-tab" tabindex="0">

{% include 'estoque/partials/saldo_diario.html' %}

</div>
</div>
</div>


{% include 'estoque/partials/saida_cadastro_modal.html' %}

{% include 'estoque/partials/entrada_cadastro_modal.html' %}

{% include 'estoque/partials/saida_edit_modal.html' %}

{% include 'estoque/partials/entrada_edit_modal.html' %}

{% include 'estoque/partials/scripts.html' %}

{% endblock %}

app/estoque/templates/estoque/relatorios.html
{% extends 'base.html' %}

{% block content %}

<div>
  <a href="{{ url_for('main.estoque_menu') }}" class="btn btn-secondary m-3">
    <i class="bi bi-arrow-left"></i>
  </a>
</div>


<div class="container py-4">
    <div class="d-grid gap-3">
        <a href="{{ url_for('relatorios.relatorios_periodo') }}" class="btn btn-outline-success btn-lg">Relatórios por periodo</a>
        <a href="{{ url_for('relatorios.relatorio_produto') }}" class="btn btn-outline-success btn-lg">Relatórios de produtos</a>
    </div>
    
</div>

{% endblock %}

app/estoque/templates/estoque/relatorios_periodo.html
{% extends 'base.html' %}

{% block content %}


<div>
  <a href="{{ url_for('relatorios.relatorios_lista') }}" class="btn btn-secondary m-3">
    <i class="bi bi-arrow-left"></i>
  </a>
</div>


<div class="container py-4">
  <div class="page-title mb-4">
    <h2 class="fw-bold border-bottom pb-2">
      Relatório de {{ data_inicio | format_date }} a {{ data_fim | format_date }}
    </h2>
  </div>
</div>


<div class="container py-4">
<div class="card mb-3 shadow" style="border: 0px; height: 80px;">
    <div class="card-body">
        <form id="formData" action="{{ url_for('relatorios.relatorios_periodo') }}" 
              class="d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3 h-100", method="post">

            <input type="date" id="data_inicio" name="data_inicio" 
                   value="{{ data_inicio }}" class="form-control h-100">

            <input type="date" id="data_fim" name="data_fim" 
                   value="{{ data_fim }}" class="form-control h-100">

            <button class="btn btn-primary h-100" type="submit">Pesquisar</button>
        </form>
    </div>
</div>

</div>
<div class="container mt-5">
<div class="card mb-3 shadow" style="border: 0px; padding: 30px; border-radius: 15px;">
    <div class="card-body">
    <div class="table-responsive">

        <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Produto</th>
                <th scope="col">Unid.</th>
                <th scope="col">Café da manhã</th>
                <th scope="col">Lanche da manhã</th>
                <th scope="col">Almoço</th>
                <th scope="col">Lanche da tarde</th>
                <th scope="col">Jantar</th>
                <th scope="col">Ceia</th>
                <th scope="col">Outros</th>
                <th scope="col">Entrada</th>
            </tr>
        </thead>
        
        <tbody>

            {% for produto in produtos %}
                <tr>
                    <td scope="row">{{ produto.nome }}</td>
                    <td>{{ produto.unidade }}</td>
                    {% for refeicao in refeicoes %}
                    <td>{{ saidas_mensais[produto.id][refeicao.id] if saidas_mensais[produto.id][refeicao.id] > 0 else '' }}</td>
                    {% endfor %}
                    <td>{{ entradas_mensais[produto.id] if entradas_mensais[produto.id] > 0 else '' }}</td>
            </tr>
            {% else %}
                <p>Ainda não há produtos cadastrados</p>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
</div>
</div>

{% endblock %}

app/estoque/templates/estoque/relatorios_produto.html
{% extends 'base.html' %}

{% block content %}


<div>
  <a href="{{ url_for('relatorios.relatorios_lista') }}" class="btn btn-secondary m-3">
    <i class="bi bi-arrow-left"></i>
  </a>
</div>


<div class="container py-4">
  <div class="page-title mb-4">
    <h2 class="fw-bold border-bottom pb-2">
        Relatório por produto
    </h2>
  </div>
</div>

<div class="container py-4">

<div class="card mb-3 shadow" style="border: 0px; height: 80px;">
    <div class="card-body">
      <form id="formProduto" action="{{ url_for('relatorios.relatorio_produto') }}" class="d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3 h-100" method="post">
            <select name="produto_select" id="produto_select" class="form-control h-100">
              {% for produto in produtos %}
                    {% if produto_id == produto.id %}
                        <option value="{{ produto.id }}" selected>{{ produto.nome }}</option>
                    {% else %}
                        <option value="{{ produto.id }}">{{ produto.nome }}</option>
                    {% endif %}
              {% endfor %}
            </select>
            <button class="btn btn-primary h-100" type="submit">Pesquisar</button>
      </form>
</div>
</div>
</div>


<div class="container py-4">
  <div class="page-title mb-4">
    <h3 class="fw-bold border-bottom pb-2">
      Consumo anual
    </h3>
  </div>
  <img src="data:image/png;base64,{{ grafico_1 }}" alt="Gráfico" style="width: 900px; height: 550px;">
</div>


<div class="container py-4">
  <div class="page-title mb-4">
    <h3 class="fw-bold border-bottom pb-2">
      Consumo médio por refeição
    </h3>
  </div>
  <img src="data:image/png;base64,{{ grafico_2 }}" alt="Gráfico" style="width: 900px; height: 550px;">
</div>


{% endblock %}