app/estoque/routes.py
from flask import Blueprint, request, session, render_template, redirect, flash, url_for
from datetime import date, datetime
from sqlalchemy.orm import Session as S

from app.utils import login_required, role_required
from app.database.db import *
from app.database.utils import *
from app.utils import somar_dia
from app.estoque.models import *
from app.models import *
from app.empenho.models import *
from app.usuarios.models import Usuario

estoque_bp = Blueprint('estoque', __name__, template_folder='templates')


@estoque_bp.route('/movimentacoes-diarias', methods=['POST', 'GET'])
@login_required
def movimentacoes_diarias():
    tipo_movimentacao = request.values.get('tipo_movimentacao')
    if not tipo_movimentacao:
        tipo_movimentacao = session.pop('tipo_movimentacao', None)
    if not tipo_movimentacao:
        tipo_movimentacao = 'saida'

    data = request.form.get('date')
    if data == None:
        data = session.pop('date', None)
    if data == None:
        data = date.today().isoformat()

    with get_session() as session_db:
        entradas_diarias = session_db.query(Entrada).filter_by(data_entrada=data).order_by(Entrada.produto_id).all()
        saidas_diarias = session_db.query(Saida).filter_by(data_saida=data).order_by(Saida.refeicao_id).order_by(Saida.produto_id).all()

        produtos_dict, fornecedores_dict, marcas_dict, refeicoes = get_additional_info(session_db)
        saldos_diarios = session_db.query(SaldoDiario).filter_by(data=data).all()
        nfs_1 = session_db.query(
            NotaFiscal
        ).join(
            Empenho, Empenho.id == NotaFiscal.empenho_id
        ).join(
            Ata, Ata.id == Empenho.ata_id
        ).filter(
            Ata.tipo == 'nao_perecivel'
        ).group_by(
            NotaFiscal.id
        ).all()
        nfs_2 = session_db.query(NotaFiscal).filter_by(id=1).all()
        nota_fiscal_dict = {nf.id: nf for nf in nfs_2 + nfs_1}

        dia = session_db.query(DiasFechados).filter_by(data=data).first()

        movs = entradas_diarias.copy()
        movs.extend(saidas_diarias.copy())

        usuarios = {}
        for mov in movs:
            if mov.usuario_id not in usuarios.keys():
                usuario = session_db.query(Usuario).filter_by(id=mov.usuario_id).first()
                if usuario:
                    usuarios[usuario.id] = usuario.nome
                else:
                    usuarios[mov.usuario_id] = 'Desconhecido'

    return render_template(
        'estoque/movimentacoes_diarias.html',
        saidas=saidas_diarias,
        data=data,
        produtos=produtos_dict,
        entradas=entradas_diarias,
        saldos_diarios=saldos_diarios,
        dia=dia,
        usuarios=usuarios,
        fornecedores=fornecedores_dict,
        marcas=marcas_dict,
        notas_fiscais=nota_fiscal_dict,
        refeicoes=refeicoes,
        tipo_movimentacao=tipo_movimentacao
    )

@estoque_bp.route('/fechar/dia/<data>')
@login_required
@role_required('admin', 'nutricionista')
def fechar_dia(data: str):
    cod = verificar_dias_abertos()
    if cod == 1:
        flash('Não há dia aberto', 'danger')
        return
    
    try:
        with get_session() as session_db:
            saldos_ = session_db.query(SaldoDiario).filter_by(data=data).all()

            if not check_saldo(data, session_db):
                return redirect(url_for('estoque.movimentacoes_diarias', date=data))

            dia = session_db.query(DiasFechados).filter_by(data=data).first()
            dia.fechado = True

            # Soma 1 dia a data
            new_date = somar_dia(data, '%Y-%m-%d')

            dia = DiasFechados(data=new_date, fechado=False)
            session_db.add(dia)

            for saldo in saldos_:
                new_saldo = SaldoDiario(produto_id=saldo.produto_id, data=new_date, quantidade_inicial=saldo.quantidade_final, quantidade_entrada=0, quantidade_saida=0, quantidade_final=saldo.quantidade_final)
                session_db.add(new_saldo)
    except Exception as e:
        flash(f'Falha ao fechar dia: {data}', 'danger')
    else:
        try:
            data_formatada = datetime.strptime(data, "%Y-%m-%d").strftime("%d/%m/%Y")
            flash(f"Dia {data_formatada} fechado com sucesso", 'success')
        except Exception as e:
            flash(f'Dia {data} fechado com sucesso', 'success')
    
    session['date'] = data
    return redirect(url_for('estoque.movimentacoes_diarias'))




def get_additional_info(session_db: S):
    produtos_dict = {p.id: p for p in session_db.query(Produto).all()}
    fornecedores_dict = {f.id: f for f in session_db.query(Fornecedor).all()}
    marcas_dict = {m.id: m for m in session_db.query(Marca).order_by(Marca.nome).all()}
    refeicoes = {d.id: d for d in session_db.query(Refeicao).all()}

    return produtos_dict, fornecedores_dict, marcas_dict, refeicoes



@estoque_bp.route('/movimentacao/<int:produto_id>/')
@login_required
def movimentacao_por_produto(produto_id):
    page = request.args.get('page', default=1, type=int)
    p_page = 20
    offset = (page - 1) * p_page
    movimentacoes: list[dict] = []
    logs_saidas = {}
    logs_entradas = {}
    total = 0
    
    try:
        movimentacoes, total = list_movementation_by_product(produto_id, p_page, offset)
        with get_session() as session_db:
            produto = session_db.query(Produto).filter_by(id=produto_id).first()
            refeicoes = {d.id: d for d in session_db.query(Refeicao).all()}
            usuarios = {u.id: u for u in session_db.query(Usuario).all()}
            
            for movimentacao in movimentacoes:
                log = session_db.query(Log).filter_by(operacao_id=movimentacao.get('id')).filter_by(tipo_operacao_2='inserção').filter_by(tipo_operacao=movimentacao.get('tipo')).first()
                if log:
                    if movimentacao.get('tipo') == 'saida':
                        logs_saidas[movimentacao['id']] = log
                    elif movimentacao.get('tipo') == 'entrada':
                        logs_entradas[movimentacao['id']] = log

    except Exception as e:
        flash(f'{e}', 'danger')
        return redirect('/')
    
    if produto == None:
        flash('Produto não encontrado', 'danger')
        return redirect('/')
    
    produto.nome = produto.nome.replace('\n', ' ')
    total_pages = (total + p_page - 1) // p_page

    return render_template('estoque/movimentacao_por_produto.html', movimentacoes=movimentacoes, produto=produto, refeicoes=refeicoes, page=page, total_pages=total_pages, usuarios=usuarios, logs_saidas=logs_saidas, logs_entradas=logs_entradas)


def verificar_dias_abertos() -> int:
    try:
        with get_session() as session_db:
            dias_ = session_db.query(DiasFechados).filter_by(fechado=False).all()

            if len(dias_) == 0:
                mais_recente = session_db.query(DiasFechados).filter_by(fechado=True).order_by(DiasFechados.data.desc()).first()
                if mais_recente == None:
                        return 1
            
            elif len(dias_) > 1:
                for dia in dias_[:-1]:
                    dia.fechado = True
                return 2
    except Exception as e:
        flash(f'Não foi possivel verificar os dias: {e}', 'danger')
        return 3
    
    return 0

app/estoque/templates/estoque/partials/entrada_cadastro_modal.html
<div class="modal fade" id="addEntradaModal" tabindex="-1" aria-labelledby="addEntradaModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    <form action="{{ url_for('entradas.cadastro_entrada') }}" method="POST">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="addEntradaModalLabel">Adicionar entrada</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
            <div class="mb-3">
                <label for="produto_id" class="form-label">Produto</label>
                <select id="produto_id" name="produto_id" class="form-select">
                    {% for produto_id, produto in produtos.items() %}
                    {% if produto.status == 'ativo' and produto.tipo.value == 'nao_perecivel' %}
                        <option value="{{ produto_id }}">{{ produto.nome }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
            </div>

              <input id="data_entrada" name="data_entrada" type="date" class="form-control" value="{{ data }}" hidden required>

            <div class="mb-3">
                <label for="quantidade" class="form-label">Quantidade</label>
                <input id="quantidade" name="quantidade" type="number" class="form-control" required>
            </div>

            <div class="mb-3">
                <label for="marca_id" class="form-label">Marca</label>
                <select id="marca_id" name="marca_id" class="form-select">
                  <option value="0">Selecione uma marca</option>
                  {% for marca_id, marca in marcas.items() %}
                  {% if marca.nome != "-" %}
                  <option value="{{ marca_id }}">{{ marca.nome }}</option>
                  {% endif %}
                  {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="data_validade" class="form-label">Data de Validade</label>
                <input id="data_validade" name="data_validade" type="date" class="form-control">
            </div>

            <div class="mb-3">
                <label for="fornecedor_id" class="form-label">Fornecedor</label>
                <select id="fornecedor_id" name="fornecedor_id" class="form-select">
                  <option value="0">Selecione um fornecedor</option>
                  {% for fornecedor_id, fornecedor in fornecedores.items() %}
                  {% if fornecedor.nome != "-" and fornecedor.status.value == 'ativo' %}
                  <option value="{{ fornecedor_id }}">{{ fornecedor.nome }}</option>
                  {% endif %}
                  {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="nota_fiscal_id" class="form-label">Nota fiscal</label>
                <select id="nota_fiscal_id" name="nota_fiscal_id" class="form-select">
                  <option value="0">Selecione uma nota fiscal</option>
                  {% for nota_fiscal_id, nota_fiscal in notas_fiscais.items() %}
                  {% if nota_fiscal.numero != "-" %}
                  <option value="{{ nota_fiscal_id }}">{{ nota_fiscal.numero }}</option>
                  {% endif %}
                  {% endfor %}
                </select>
            </div>
            
            <div class="mb-3">
                <label for="observacao" class="form-label">Observação</label>
                <input id="observacao" name="observacao" type="text" class="form-control">
            </div>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
        </form>
      </div>
    </div>
  </div>

app/estoque/templates/estoque/partials/entrada_edit_modal.html
<div class="modal fade" id="editEntradaModal" tabindex="-1" aria-labelledby="editEntradaModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    <form id="editEntradaForm" method="POST">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="editEntradaModalLabel">Editar entrada</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
            <div class="mb-3">
                <label for="edit_produto_id_entrada" class="form-label">Produto</label>
                <select id="edit_produto_id_entrada" name="edit_produto_id_entrada" class="form-select" disabled>
                    {% for produto_id, produto in produtos.items() %}
                    {% if produto.status == 'ativo' %}
                        <option value="{{ produto_id }}">{{ produto.nome }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
            </div>
            
            <div class="mb-3">
                <label for="edit_data_entrada" class="form-label">Data</label>
                <input id="edit_data_entrada" name="edit_data_entrada" type="date" class="form-control" value="{{ data }}" disabled>
            </div>
            
            <div class="mb-3">
                <label for="edit_quantidade_entrada" class="form-label">Quantidade</label>
                <input id="edit_quantidade_entrada" name="edit_quantidade_entrada" type="number" class="form-control" required>
            </div>

            <div class="mb-3">
                <label for="edit_marca_id_entrada" class="form-label">Marca</label>
                <select id="edit_marca_id_entrada" name="edit_marca_id_entrada" class="form-select">
                  {% for marca_id, marca in marcas.items() %}
                    <option value="{{ marca_id }}">{{ marca.nome }}</option>
                  {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="edit_data_validade_entrada" class="form-label">Data de Validade</label>
                <input id="edit_data_validade_entrada" name="edit_data_validade_entrada" type="date" class="form-control" required>
            </div>

            <div class="mb-3">
                <label for="edit_fornecedor_id_entrada" class="form-label">Fornecedor</label>
                <select id="edit_fornecedor_id_entrada" name="edit_fornecedor_id_entrada" class="form-select">
                  {% for fornecedor_id, fornecedor in fornecedores.items() %}
                  {% if fornecedor.status.value == 'ativo' %}
                    <option value="{{ fornecedor_id }}">{{ fornecedor.nome }}</option>
                  {% endif %}
                  {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="edit_nota_fiscal_id_entrada" class="form-label">Nota fiscal</label>
                <select id="edit_nota_fiscal_id_entrada" name="edit_nota_fiscal_id_entrada" class="form-select">
                  {% for nota_fiscal_id, nota_fiscal in notas_fiscais.items() %}
                    <option value="{{ nota_fiscal_id }}">{{ nota_fiscal.numero }}</option>
                  {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="edit_observacao_entrada" class="form-label">Observação</label>
                <input id="edit_observacao_entrada" name="edit_observacao_entrada" type="text" class="form-control">
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
        </form>
      </div>
    </div>
  </div>

app/estoque/templates/estoque/partials/entradas_table.html
{% if ['admin', 'nutricionista'] | check_intersection(session.get('roles', [])) %}
{% if dia and not dia.fechado %}
<div style="display: flex; justify-content: center; margin-top: 15px;">
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addEntradaModal" style="margin: 10px;">
    Cadastrar nova entrada
  </button>
</div>
{% endif %}
{% endif %}

<div class="container mt-5">
<div class="card mb-3 shadow" style="border: 0px; padding: 30px; border-radius: 15px;">
  <div class="card-body">
  <button id="toggleDetalheEntradaBtn" class="btn btn-primary mb-3">Ver resumo</button>
    <div class="table-responsive" style="overflow-x: auto; width: 100%;">

        <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Cód.</th>
                <th scope="col">Nome</th>
                <th scope="col">Unid.</th>
                <th scope="col">Qntd.</th>
                <th scope="col" class="col-detalhe-entrada">Marca</th>
                <th scope="col" class="col-detalhe-entrada">Validade</th>
                <th scope="col" class="col-detalhe-entrada">Fornecedor</th>
                <th scope="col" class="col-detalhe-entrada">Nota fiscal</th>
                <th scope="col" class="col-detalhe-entrada">Observação</th>
                <th scope="col" class="col-detalhe-entrada">Responsavel</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
          {% for entrada in entradas %}
          <tr>
              <td>{{ produtos.get(entrada.produto_id).codigo }}</td>
              <td>{{ produtos.get(entrada.produto_id).nome }}</td>
              <td>{{ produtos.get(entrada.produto_id).unidade }}</td>
              <td>{{ entrada.quantidade }}</td>
              <td class="col-detalhe-entrada">{{ marcas.get(entrada.marca_id).nome }}</td>
              <td class="col-detalhe-entrada">{{ entrada.data_validade | format_date }}</td>
              <td class="col-detalhe-entrada">{{ fornecedores.get(entrada.fornecedor_id).nome }}</td>
              <td class="col-detalhe-entrada">{{ notas_fiscais.get(entrada.nota_fiscal_id).numero }}</td>
              <td class="col-detalhe-entrada">{{ entrada.observacao }}</td>
              <td class="col-detalhe-entrada">{{ usuarios.get(entrada.usuario_id) }}</td>
              <td>
                {% if dia != None %}
                  {% if dia.fechado == False and ['admin', 'nutricionista'] | check_intersection(session.get('roles', [])) %}
                  <div style="display: flex; gap: 10px;">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editEntradaModal" onclick="fillEntradaEditForm('{{entrada.id}}', '{{entrada.produto_id}}', '{{entrada.data_entrada}}', '{{entrada.quantidade}}', '{{entrada.marca_id}}', '{{entrada.data_validade}}', '{{entrada.fornecedor_id}}', '{{entrada.nota_fiscal_id}}', '{{entrada.observacao}}')">Editar</button>
                    <form action="{{ url_for('entradas.excluir_entrada', entrada_id=entrada.id) }}" method="POST" onsubmit="return confirm('Tem certeza que deseja excluir esta entrada?')">
                      <button type="submit" class="btn btn-danger">Excluir</button>
                    </form>
                  </div>
                  {% else %}
                  <div style="display: flex; gap: 10px;">
                    <button class="btn btn-secondary" onclick="alert('Você não tem permissão para editar este item.')">Editar</button>
                    <button class="btn btn-secondary" onclick="alert('Você não tem permissão para excluir este item.')">Excluir</button>
                  </div>
                  {% endif %}
                  {% else %}
                  <div style="display: flex; gap: 10px;">
                    <button class="btn btn-secondary" onclick="alert('Você não tem permissão para editar este item.')">Editar</button>
                    <button class="btn btn-secondary" onclick="alert('Você não tem permissão para excluir este item.')">Excluir</button>
                  </div>
                  {% endif %}
              </td>
          {% endfor %}
          </tbody>
</table>
</div>
</div>
</div>
</div>

app/estoque/templates/estoque/partials/saida_cadastro_modal.html
<div class="modal fade" id="addSaidaModal" tabindex="-1" aria-labelledby="addSaidaModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    <form action="{{ url_for('saidas.cadastro_saida') }}" method="POST">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="addSaidaModalLabel">Adicionar saida</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
            <div class="mb-3">
                <label for="produto_id" class="form-label">Produto</label>
                <select id="produto_id" name="produto_id" class="form-select">
                    {% for produto_id, produto in produtos.items() %}
                    {% if produto.status == 'ativo' and produto.tipo.value == 'nao_perecivel' %}
                        <option value="{{ produto_id }}">{{ produto.nome }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="refeicao_id" class="form-label">Refeição</label>
                <select id="refeicao_id" name="refeicao_id" class="form-select">
                    {% for refeicao_id, refeicao in refeicoes.items() %}
                        <option value="{{ refeicao_id }}">{{ refeicao.nome }}</option>
                    {% endfor %}
                </select>
            </div>
            
              <input id="data_saida" name="data_saida" type="date" class="form-control" value="{{ data }}" hidden required>
            
            <div class="mb-3">
                <label for="quantidade" class="form-label">Quantidade</label>
                <input id="quantidade" name="quantidade" type="number" class="form-control" required>
            </div>

            <div class="mb-3">
                <label for="marca_id" class="form-label">Marca</label>
                <select id="marca_id" name="marca_id" class="form-select">
                  <option value="0">Selecione uma marca</option>
                  {% for marca_id, marca in marcas.items() %}
                  {% if marca.nome != "-" %}
                    <option value="{{ marca_id }}">{{ marca.nome }}</option>
                  {% endif %}
                  {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="data_validade" class="form-label">Data de Validade</label>
                <input id="data_validade" name="data_validade" type="date" class="form-control">
            </div>

            <div class="mb-3">
                <label for="fornecedor_id" class="form-label">Fornecedor</label>
                <select id="fornecedor_id" name="fornecedor_id" class="form-select">
                  <option value="0">Selecione um fornecedor</option>
                  {% for fornecedor_id, fornecedor in fornecedores.items() %}
                  {% if fornecedor.nome != "-" and fornecedor.status.value == 'ativo' %}
                    <option value="{{ fornecedor_id }}">{{ fornecedor.nome }}</option>
                  {% endif %}
                  {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="nota_fiscal_id" class="form-label">Nota fiscal</label>
                <select id="nota_fiscal_id" name="nota_fiscal_id" class="form-select">
                  <option value="0">Selecione uma nota fiscal</option>
                  {% for nota_fiscal_id, nota_fiscal in notas_fiscais.items() %}
                  {% if nota_fiscal.numero != "-" %}
                    <option value="{{ nota_fiscal_id }}">{{ nota_fiscal.numero }}</option>
                  {% endif %}
                  {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="observacao" class="form-label">Observação</label>
                <input id="observacao" name="observacao" type="text" class="form-control">
            </div>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
        </form>
      </div>
    </div>
  </div>

app/estoque/templates/estoque/partials/saida_edit_modal.html
<div class="modal fade" id="editSaidaModal" tabindex="-1" aria-labelledby="editSaidaModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    <form id="editSaidaForm" method="POST">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="editSaidaModalLabel">Editar saida</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
            <div class="mb-3">
                <label for="edit_produto_id_saida" class="form-label">Produto</label>
                <select id="edit_produto_id_saida" name="edit_produto_id_saida" class="form-select" disabled>
                    {% for produto_id, produto in produtos.items() %}
                    {% if produto.status == 'ativo'  %}
                        <option value="{{ produto_id }}">{{ produto.nome }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="edit_refeicao_id_saida" class="form-label">Refeição</label>
                <select id="edit_refeicao_id_saida" name="edit_refeicao_id_saida" class="form-select">
                    {% for refeicao_id, refeicao in refeicoes.items() %}
                        <option value="{{ refeicao_id }}">{{ refeicao.nome }}</option>
                    {% endfor %}
                </select>
            </div>
            
            <div class="mb-3">
                <label for="edit_data_saida" class="form-label">Data</label>
                <input id="edit_data_saida" name="edit_data_saida" type="date" class="form-control" value="{{ data }}" disabled>
            </div>
            
            <div class="mb-3">
                <label for="edit_quantidade_saida" class="form-label">Quantidade</label>
                <input id="edit_quantidade_saida" name="edit_quantidade_saida" type="number" class="form-control" required>
            </div>

            <div class="mb-3">
                <label for="edit_marca_id_saida" class="form-label">Marca</label>
                <select id="edit_marca_id_saida" name="edit_marca_id_saida" class="form-select">
                  {% for marca_id, marca in marcas.items() %}
                    <option value="{{ marca_id }}">{{ marca.nome }}</option>
                  {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="edit_data_validade_saida" class="form-label">Data de Validade</label>
                <input id="edit_data_validade_saida" name="edit_data_validade_saida" type="date" class="form-control" required>
            </div>

            <div class="mb-3">
                <label for="edit_fornecedor_id_saida" class="form-label">Fornecedor</label>
                <select id="edit_fornecedor_id_saida" name="edit_fornecedor_id_saida" class="form-select">
                  {% for fornecedor_id, fornecedor in fornecedores.items() %}
                  {% if fornecedor.status.value == 'ativo' %}
                    <option value="{{ fornecedor_id }}">{{ fornecedor.nome }}</option>
                  {% endif %}
                  {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="edit_nota_fiscal_id_saida" class="form-label">Nota fiscal</label>
                <select id="edit_nota_fiscal_id_saida" name="edit_nota_fiscal_id_saida" class="form-select">
                  {% for nota_fiscal_id, nota_fiscal in notas_fiscais.items() %}
                    <option value="{{ nota_fiscal_id }}">{{ nota_fiscal.numero }}</option>
                  {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="edit_observacao_saida" class="form-label">Observação</label>
                <input id="edit_observacao_saida" name="edit_observacao_saida" type="text" class="form-control">
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
        </form>
      </div>
    </div>
  </div>

app/estoque/templates/estoque/partials/saldo_diario.html
{% if ['admin', 'nutricionista'] | check_intersection(session.get('roles', [])) %}
{% if dia and not dia.fechado %}
<div style="display: flex; justify-content: center; margin-bottom: 15px; margin-top: 25px;">
  <a type="button" class="btn btn-primary" href="{{ url_for('estoque.fechar_dia', data=data) }}" onclick="return confirm('Tem certeza que deseja fechar o dia?')">Fechar dia</a>
</div>
{% endif %}
{% endif %}

<div class="container mt-5">
<div class="card mb-3 shadow" style="border: 0px; padding: 30px; border-radius: 15px;">
    <div class="table-responsive">

        <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Cód.</th>
                <th scope="col">Produto</th>
                <th scope="col">Qntd. inicial</th>
                <th scope="col">Qntd. entrada</th>
                <th scope="col">Qntd. saida</th>
                <th scope="col">Qntd. final</th>
            </tr>
        </thead>
        
        <tbody>

            {% for saldo in saldos_diarios %}
            {% if produtos.get(saldo.produto_id).status == 'ativo' or 'admin' in session.get('roles', []) %}
                <tr>
                    <td scope="row">{{ produtos.get(saldo.produto_id).codigo }}</td>
                    <td>{{ produtos.get(saldo.produto_id).nome }}</td>
                    <td>{{ saldo.quantidade_inicial }}</td>
                    <td>{{ saldo.quantidade_entrada }}</td>
                    <td>{{ saldo.quantidade_saida }}</td>
                    {% if saldo.quantidade_final < produtos[saldo.produto_id].quantidade_minima and dia and not dia.fechado %}
                        <td style="color: red;">{{ saldo.quantidade_final }}</td>
                        {% else %}
                        <td>{{ saldo.quantidade_final }}</td>
                    {% endif %}
                </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
</div>