app/main/routes.py
from flask import Blueprint, session, render_template, redirect, url_for, flash
from datetime import date, datetime
from decimal import Decimal

from app.utils import login_required
from app.database.db import get_session
from app.estoque.models import DiasFechados, SaldoDiario
from app.models import Produto

main_bp = Blueprint('main', __name__, template_folder='templates')

@main_bp.route('/')
def index():
    if 'user_id' not in session.keys():
        return redirect(url_for('usuarios.login'))

    return render_template('main/index.html')

@main_bp.route('/sobre')
@login_required
def sobre():
    return render_template('main/sobre.html')

@main_bp.route('/estoque-menu')
@login_required
def estoque_menu():
    try:
        with get_session() as session_db:
            dia = session_db.query(DiasFechados).filter_by(fechado=False).first()
            if dia:
                produtos = session_db.query(Produto).filter_by(tipo='nao_perecivel').all()
                saldos = {s.produto_id: s for s in session_db.query(SaldoDiario).filter_by(data=dia.data).all()}
    except Exception as e:
        flash('Erro ao recuperar dia aberto!', 'danger')
        return render_template('main/index.html')
    
    produtos_zerados = []
    baixo_estoque = []
    for p in produtos:
        saldo = saldos.get(p.id)
        if not saldo or p.status == 'inativo':
            continue

        if saldo.quantidade_final == 0:
            produtos_zerados.append(p)
        elif saldo.quantidade_final < p.quantidade_minima:
            p.quantidade = saldo.quantidade_final
            baixo_estoque.append(p)
    
    return render_template('main/estoque.html', dia=dia, produtos_zerados=produtos_zerados, baixo_estoque=baixo_estoque)


@main_bp.app_errorhandler(404)
def page_not_found(error):
    return render_template('erros/404.html'), 404


@main_bp.app_errorhandler(500)
def page_not_found(error):
    return render_template('erros/500.html'), 500

@main_bp.route('/atas-menu')
@login_required
def atas_menu():
    return render_template('main/atas.html')

@main_bp.route('/registro-refeicao-menu')
@login_required
def registro_refeicao_menu():
    return render_template('main/registro_refeicao.html')


@main_bp.app_template_filter('format_date')
def format_date(value, formato='%d/%m/%Y'):
    if isinstance(value, date):
        return value.strftime(formato)
    return value


@main_bp.app_template_filter('format_money')
def format_money(value: Decimal, rs=True):
    if isinstance(value, Decimal):
        if rs:
            return f'R$ {value:,.2f}'.replace(',', 'X').replace('.', ',').replace('X', '.')
        return f'{value:,.2f}'.replace(',', 'X').replace('.', ',').replace('X', '.')
    return value

@main_bp.app_template_filter('capitalize')
def capitalize(value: str):
    try:
        string = value.capitalize()
        return string
    except Exception as e:
        print(e)
        return value
    
@main_bp.app_template_filter('replace')
def replace(value: str, old: str, new: str):
    try:
        string = value.replace(old, new)
        return string
    except:
        return value
    
@main_bp.app_template_filter('format_empenho')
def format_empenho(value: int, ano: int):
    try:
        if not ano:
            ano = str(datetime.now().year)
        
        qntd_zeros = 6 - len(str(value))
        if qntd_zeros < 0:
            return f'{ano}NE{value}'
        
        string = str(ano) + 'NE'
        for i in range(qntd_zeros):
            string += '0'
        
        string += str(value)
        return string
    except:
        return f'{ano}NE{value}'
    
@main_bp.app_template_filter('check_intersection')
def check_intersection(iteravel_1, iteravel_2):
    try:
        if any(i1 == i2 for i1 in iteravel_1 for i2 in iteravel_2):
            return True
    except:
        pass
    return False

def register_filters(app):
    app.add_template_filter(format_date, 'format_date')
    app.add_template_filter(format_money, 'format_money')
    app.add_template_filter(format_empenho, 'format_empenho')
    app.add_template_filter(capitalize, 'capitalize')
    app.add_template_filter(replace, 'replace')
    app.add_template_filter(check_intersection, 'check_intersection')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Refeitorio IFCE - Crato</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body class="d-flex flex-column min-vh-100" style="background-color: #fafafa;">
    <nav class="navbar navbar-expand-lg navbar-custom shadow-sm">
  <div class="container-fluid">

    <!-- Logo -->
    <a class="navbar-brand d-flex align-items-center" href="/">
      <img src="{{ url_for('static', filename='ifce_logo.png')}}" style="width: 70px; border-radius: 8px;">
    </a>

    <!-- Botão toggle para mobile -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Itens da navbar -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Lado esquerdo -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="/" style="color: white;">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('main.estoque_menu') }}" style="color: white;">Estoque</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('main.atas_menu' ) }}" style="color: white;">Atas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('main.registro_refeicao_menu') }}" style="color: white;">Registro de refeições</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/sobre" style="color: white;">Sobre</a>
        </li>
      </ul>

      <!-- Lado direito -->
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if 'user_id' in session %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle user-menu" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown"
             aria-expanded="false" style="color: white;">
            Olá, {{ session.get('nome', 'Usuario').split()[0] }}
          </a>
          <ul class="dropdown-menu dropdown-menu-end shadow-sm" aria-labelledby="userDropdown">
            <li><a class="dropdown-item" href="{{ url_for('usuarios.perfil_usuario') }}"><i class="bi bi-person"></i> Perfil</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item text-danger" href="/logout"><i class="bi bi-box-arrow-right"></i> Logout</a></li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="btn btn-light btn-sm px-3 fw-bold" href="/login" style="color: black;">Login</a>
        </li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>


{% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            <ul id="messages" class="list-unstyled">
                {% for categoria, message in messages %}
                    <li class="alert alert-{{ categoria }}">{{ message }}</li>
                {% endfor %}
            </ul>
            <script>
                setTimeout(function() {
                    const messageBox = document.getElementById('messages');
                    if (messageBox) {
                        messageBox.style.display = 'none';
                    }
                }, 5000); 
            </script>
        {% endif %}
    {% endwith %}

    {% block content %}
    {% endblock %}

<footer class="text-light py-4 mt-auto" style="background-color: #4CAF50;">
  <div class="container">
    <div class="row">
      <div class="col text-center">
        <p class="mb-0">&copy; 2025 Instituto Federal do Ceará.</p>
      </div>
    </div>
  </div>
</footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>
</html>

app/templates/table_base.html
<div class="container mt-5">
  <div class="card mb-3 shadow" style="border: 0px; padding: 30px; border-radius: 15px;">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
          <thead>
            {% block table_head %}
            
            {% endblock %}
          </thead>
          <tbody>
            {% block table_body %}
            
            {% endblock %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>